[build]
  publish = "public"
  command = "hugo -D -F"
  HUGO_VERSION = "0.72.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.72.0"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.72.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"
